name: Setup
description: Checkout, install, and build
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v3
      with:
        node-version: 16
        # TODO
        # check-latest: true
        cache: yarn

    - run: yarn install --immutable
      shell: bash
