service: default
runtime: python27
threadsafe: true

manual_scaling:
  instances: 1

handlers:
  - url: /(.*\.(css|eot|gz|html|ico|js|map|png|svg|ttf|woff|woff2))
    static_files: build/\1
    upload: build/(.*)
  - url: /.*
    static_files: build/index.html
    secure: always
    upload: build/index.html
